# Assignment1 

## Matrix 구현 
1. Linear Regression 에서 쓰이는 **정규방정식**을 행렬로 구현하고, sklearn 혹은 OLS 패키지를 통해 구한 **실제 값과 비교**해 주세요 
2. LSE에서 쓰이는 Loss Function, **MSE**를 행렬로 구현해 출력해 주세요 

### Data Load 

In [3]:
import pandas as pd 
data = pd.read_csv("assignment1.csv")

In [4]:
data.head()

y    x1    x2  x3   x4    x5
0  10  38.9  64.7   4  868  59.7
1  13  41.6  45.3  -4  957  61.4
2  11  39.7  74.1   8  786  61.0
3   7  37.3  48.0  19  984  67.5
4  10  39.5  51.9   6  700  57.2

In [5]:
data.shape # y:(9,1), X:(9,5)

(9, 6)

In [6]:
X = data.drop(["y"], axis=1)
y = data.y

In [7]:
# matrix 계산을 위해 numpy 형태로 바꾸어 줍니다 
X = X.to_numpy()
y = y.to_numpy()

In [8]:
X

array([[  38.9,   64.7,    4. ,  868. ,   59.7],
       [  41.6,   45.3,   -4. ,  957. ,   61.4],
       [  39.7,   74.1,    8. ,  786. ,   61. ],
       [  37.3,   48. ,   19. ,  984. ,   67.5],
       [  39.5,   51.9,    6. ,  700. ,   57.2],
       [  37.4,   53.6,   -5. , 1037. ,   58.8],
       [  35.1,   71.4,    3. ,  986. ,   58.6],
       [  38.8,   58.3,    6. ,  819. ,   59.2],
       [  36.6,   52.6,  -19. ,  791. ,   54.4]])

In [9]:
y

array([10, 13, 11,  7, 10,  9,  9,  6,  5])

### 1. Normal Equation

In [12]:
import numpy as np
from numpy.linalg import inv 

In [13]:
def estimate_beta(X, y):
    designX = np.concatenate((np.ones((data.shape[0], 1)), X), axis=1)  # 편차를 고려하기 위해 앞에 1인 column을 추가한다.
    beta_hat = np.dot(np.dot(np.linalg.inv(np.dot(designX.T, designX)),designX.T),y)  # pdf 72페이지의 행렬식을 이용하여 beta hat을 계산한다.
    
    return beta_hat

In [14]:
beta_hat = estimate_beta(X, y)
beta_hat

array([-3.92447368e+01,  1.31232583e+00,  8.53744361e-02,  7.41849897e-02,
        1.50018573e-02, -3.42273652e-01])

#### 실제 값과 비교

In [44]:
from sklearn.linear_model import LinearRegression

In [45]:
model = LinearRegression()
model.fit(X, y)

pred = model.predict(X)

In [46]:
print(model.intercept_) # intercept
print(model.coef_) # 추정된 회귀계수 (intercept제외)

-39.24473678135661
[ 1.31232583  0.08537444  0.07418499  0.01500186 -0.34227365]


실제 값과 normal equation으로 구한 값(편차를 제외한 부분)이 동일한 것을 확인할 수 있었다.

### 2. MSE

In [25]:
def MSE(X, y, beta_hat):
    designX = np.concatenate((np.ones((data.shape[0], 1)), X), axis=1)  # 편차를 고려하기 위해 앞에 1인 column을 추가한다.
    y_pred = np.dot(designX, beta_hat)
    mse = np.sum((y_pred-y)**2, axis = None)  # pred와 y를 elementwise 차이를 구하고 제곱을 한 후 평균을 구한다.
    mse /= X.shape[0]-X.shape[1]-1
    return mse

In [26]:
MSE(X, y, estimate_beta(X, y))

4.846793168705742

### 3.MLE

#### 바구니 안에 파란구슬과 빨간구슬이 들어있을 때, 10개를 추출하여보니 파란구슬이 2개 빨간구슬이 8개가 추출되었습니다. 
#### 이때 바구니안에는 파란구슬과 빨간구슬이 각각 몇개있는지에 대해서 최대우도추정법을 이용해 논리적으로 설명해주세요. 
- 수식은 있어도 좋고 말로 풀어쓰셔도 좋습니다
- 추출은 복원추출을 전제로 합니다
- 글자수 제한은 없습니다. 많이 쓰라는 얘기가 아니라 정말 제한이 없습니다. 너무 부담가지고 쓰지마세요.

바구니에서 구슬을 하나 추출하였을 때, 빨간구슬일 확률을 $\pi$ 라 하자.

그러면 관측값 $y_i=0.8$에서의 확률분포는 $f(y_i)=\pi^{y_i}(1-\pi)^{1-y_i}$


wolframalpha를 이용하여 확률이 최대가 되는 $\pi$를 구한 결과, $\pi={4\over 5}=0.8$로 추정된다.

따라서 MLE를 이용하면 빨간구슬이 뽑힐 확률은 80%정도로 추정할 수 있다.